### ISSUE TITLE
The example doesn't compile

### ISSUE THREAD

**Issue by mulle-nat** [aperezdc/cflag#1]
The example has lots of bugs. 

1. You can't make the "options" array  static, because you are using runtime values to initialize it. It works, if you remove `static` or make the option value variables static (or global).
2. The `cflag_apply("[options] --url URL", &argc, &argv);` statement is wrong. It should be `cflag_apply( options, "[options] --url URL", &argc, &argv);`.
3. For `EXIT_SUCCESS` you need `#include <stdlib.h>`
4. For `bool` you need `#include <stdbool.h>`.

**Comment by aperezdc** [comment]
I fixed 1. and 2. in https://github.com/aperezdc/cflag/commit/9c67617d0d4f34f6fb70424adfd9ceb70b346131; the missing headers I think it's okay to leave out because I would expect an average C programmer to know about adding the headers. OTOH, I have added the example with a few additions more in the `test.c` file in https://github.com/aperezdc/cflag/commit/172f04e352bbff482b379c4b6b63f9c6d4175d34. So I think we can close this.
